#!/bin/bash -l

echo "PACKAGECLOUD_USERNAME=${PACKAGECLOUD_USERNAME}"
echo "PACKAGECLOUD_REPONAME=${PACKAGECLOUD_REPONAME}"
echo "PACKAGECLOUD_DISTRO=${PACKAGECLOUD_DISTRO}"
echo "PACKAGE_NAME=${PACKAGE_NAME}"

UPLOAD_PATH="${PACKAGECLOUD_USERNAME}/${PACKAGECLOUD_REPONAME}/${PACKAGECLOUD_DISTRO}"

echo "Pushing package: ${PACKAGE_NAME}"
echo "To repository: ${UPLOAD_PATH}"

package_cloud push ${UPLOAD_PATH} ${PACKAGE_NAME}
